import axios from "axios";
import type {
  GetServerSideProps,
  GetStaticPropsResult,
  InferGetServerSidePropsType,
  NextPage,
  NextPageContext,
} from "next";
import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { AuthContext } from "../components/AuthProvider/AuthProvider";
import { RootState } from "../store/modules";
import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  // if you want to use getServerSideProps in next js,
  // you must specify the whole api since the client server will execute it
  // const sample = (await axios.get("http://localhost:5000/api")).data;
  // return {
  //   props: {
  //     sample,
  //   },
  // };
  return {
    props: { sample: "hi" },
  };
};

const Home: NextPage = ({
  sample,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const { onLogout } = useContext(AuthContext);
  const isAuthenticated = useSelector(
    (state: RootState) => state.auth.isAuthenticated
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home Page</h1>
        <p>Welcome!</p>
        <p>You are {isAuthenticated ? "loginned" : "not loginned"}</p>
        <Link href="login">Login</Link>
        <Link href="register">Register</Link>
        <Link href="account">Account Info</Link>
        <Link href="account/find">Find ID/Password</Link>
        <button onClick={onLogout}>logout</button>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
