import axios from "axios";
import type {
  GetServerSideProps,
  GetStaticPropsResult,
  InferGetServerSidePropsType,
  NextPage,
  NextPageContext,
} from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  // if you want to use getServerSideProps in next js,
  // you must specify the whole api since the client server will execute it
  // const sample = (await axios.get("http://localhost:5000/api")).data;
  // return {
  //   props: {
  //     sample,
  //   },
  // };
  return {
    props: { sample: "hi" },
  };
};

const Home: NextPage = ({
  sample,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>홈페이지</h1>
        <p>환영합니다!</p>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
